# Generated by Django 4.2.3 on 2023-07-06 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled')], default='Pending', max_length=50)),
                ('name_of_business', models.CharField(max_length=100)),
                ('business_contact', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('number_of_employee', models.IntegerField()),
                ('number_of_new_hires', models.IntegerField(blank=True, null=True)),
                ('level_of_recruitment', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'unpaid')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraduatesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled')], default='Pending', max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user')),
                ('phone', models.CharField(max_length=15)),
                ('cv', models.FileField(blank=True, null=True, upload_to='files')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
