# Generated by Django 4.2.3 on 2023-07-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, default='agile.jfif', upload_to='user/volunteer'),
        ),
    ]
