# Generated by Django 4.2.3 on 2023-09-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatesdetail',
            name='working_status',
            field=models.CharField(blank=True, choices=[('Looking for job', 'Looking for job'), ('Internship', 'Internship'), ('Working', 'Working')], default='Looking for job', max_length=100, null=True),
        ),
    ]
