# Generated by Django 4.2.3 on 2023-07-06 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0002_businessdetail_graduatesdetail_delete_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='salary',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
