# Generated by Django 4.2.3 on 2023-09-21 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0003_jobmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='jobmessage',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
