# Generated by Django 4.2.3 on 2023-08-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0003_alter_volunteer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiyumi.graduatesdetail'),
        ),
    ]
