# Generated by Django 4.2.3 on 2023-09-21 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0004_remove_jobmessage_user_jobmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='jobmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
