# Generated by Django 4.2.3 on 2023-07-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0005_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Interns', 'Interns'), ('Volunteer', 'Volunteer'), ('Business', 'Business')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduatesdetail',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Interns', 'Interns'), ('Volunteer', 'Volunteer'), ('Business', 'Business')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
