# Generated by Django 4.2.3 on 2023-07-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0006_businessdetail_role_graduatesdetail_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
