# Generated by Django 4.2.3 on 2023-09-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0006_remove_jobmessage_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.ManyToManyField(blank=True, to='apiyumi.jobmessage'),
        ),
    ]
