# Generated by Django 4.2.3 on 2023-07-11 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0007_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled')], default='Pending', max_length=50)),
                ('role_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='number_of_new_hires',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='salary',
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='number_of_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled')], default='Pending', max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(upload_to='resume')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiyumi.role'),
        ),
        migrations.AlterField(
            model_name='graduatesdetail',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiyumi.role'),
        ),
    ]
