# Generated by Django 4.2.3 on 2023-07-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0008_role_remove_businessdetail_number_of_new_hires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduatesdetail',
            name='cv',
        ),
    ]
