# Generated by Django 4.2.3 on 2023-09-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0010_rename_user_program_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='total_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
