# Generated by Django 4.2.3 on 2023-07-12 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0010_remove_resume_user_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatesdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/graduate'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled')], default='Pending', max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='user/volunteer')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiyumi.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
