# Generated by Django 4.2.3 on 2023-08-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0011_job_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='resume',
        ),
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_resume', to='apiyumi.resume'),
        ),
    ]
