# Generated by Django 4.2.3 on 2023-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0011_program_total_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
