# Generated by Django 4.2.3 on 2023-07-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0011_alter_graduatesdetail_image_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/logo'),
        ),
    ]
