# Generated by Django 4.2.3 on 2023-09-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0012_program_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='document',
        ),
    ]
