# Generated by Django 4.2.3 on 2023-08-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0013_alter_job_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
