# Generated by Django 4.2.3 on 2023-09-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0013_remove_program_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled')], default='Pending', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiyumi.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
