# Generated by Django 4.2.3 on 2023-09-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0014_programdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='resume',
            new_name='applied_graduates',
        ),
    ]
