# Generated by Django 4.2.3 on 2023-09-17 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0014_alter_businessdetail_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(blank=True, related_name='job_applied_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
