# Generated by Django 4.2.3 on 2023-09-17 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiyumi', '0015_alter_job_applied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_by',
            field=models.ManyToManyField(blank=True, related_name='event_registed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
