# Generated by Django 4.2.3 on 2023-09-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0016_alter_event_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
