# Generated by Django 4.2.3 on 2023-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0017_event_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatesdetail',
            name='working_status',
            field=models.CharField(choices=[('Looking For Job', 'Looking For Job'), ('Internship', 'Internship'), ('Working', 'Working')], default='Looking For Job', max_length=100),
        ),
    ]
