# Generated by Django 4.2.3 on 2023-09-19 06:39

import apiyumi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiyumi', '0018_graduatesdetail_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatesdetail',
            name='working_status',
            field=models.IntegerField(choices=[(1, 'UNEMPLOYED'), (2, 'INTERNSHIP'), (3, 'EMPLOYED')], default=apiyumi.models.WorkingStatus['UNEMPLOYED']),
        ),
    ]
